sudo: required

dist: trusty

language: node_js

node_js:
 - "7"

before_install:
 - rm -rf node_modules
 - npm install -g cross-env webpack npm-run-all typescript ts-node
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

install:
 - npm install

script:
 - npm run build
 - npm test
